### ISSUE TITLE
Add ability to get cookies via the HTTP API (Elmo)

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#19]
It is currently difficult to determine what the monster knows about a particular data object (i.e. what's in the cookie that relates to that object). It would be useful if Elmo could allow access to this information.

**Comment by Xophmeister** [comment]
I agree...but the reason this wasn't done from the outset is because Elmo is a generic HTTP API wrapper to any submodule. Currently this is limited to just the Cookie Jar, which doesn't expose any introspection functionality, as it's not its primary function. It seems appropriate to add such functionality and then that can be quickly wrapped up and exposed by Elmo.

(In the meantime, the data is readily accessible from the CouchDB server.)
