### ISSUE TITLE
`BiscuitTin` notifies listeners to enrichment of Cookie before DB is updated

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#32]
My understanding is that `BiscuitTin.enrich_cookie` upserts an enrichment and then notifies listeners that there's something to process in the jar. The issue is that if a listener calls `get_next_for_processing` before the buffer is flushed, it will get `None` as this query is completed before the enrichment. This leads to an unprocessed cookie being in the jar that the listeners don't know about. 

Can't be 100% sure about this as I haven't looked too deeply into what exactly `Sofabed`, `Bert` and `Ernie` are doing....

**Comment by Xophmeister** [comment]
Yes, you're right: the buffering now implies that the notification is done when the enrichment is pushed to the buffer, which isn't necessarily the same time as when it's written to the DB... I'll look into this.

**Comment by colin-nolan** [comment]
As discussed earlier, a solution could be to move to a push or poll based approach. If the system is to be scaled or if the subsystems (cookie jar, processors, retrievers) are to be fully separated, it would be necessary to use this approach.

**Comment by Xophmeister** [comment]
Another solution, which I am strongly considering, is to first check the upsert queue and buffer (so it acts as an in-memory cache) whenever a fetch is requested.

**Comment by Xophmeister** [comment]
It has occurred to me, while working on the `bugfix/32-memCache` branch, that a true in-memory cache would need to be queryable. Otherwise, any query run against the database would omit true hits that exist in the cache but have yet to be pushed. That would be bad... Thus, a true in-memory cache would amount to writing an in-memory version of CouchDB (or some kind of interoperability layer), which is obviously not the correct path to take.

Therefore, consider the `bugfix/32-memCache` branch to be misnamed. I will continue the work on refactoring the CouchDB code, so it is better modularised, and fix this bug by polling. That's not an elegant solution, but a stopgap* until we break the components apart into standalone systems.

(* Standard disclaimer/wisdom that temporary solutions are never temporary... :stuck_out_tongue:)
