### ISSUE TITLE
Large bottleneck in `BiscuitTin`'s `get_next_for_processing` method

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#39]
The time taken to return from `BiscuitTin`'s `get_next_for_processing` method is currently dominating the total time spent processing a cookie.

Most of the time is been spent blocked on this lock:
https://github.com/wtsi-hgi/cookie-monster/blob/master/cookiemonster/cookiejar/biscuit_tin.py#L522
In my current setup, the ~80 threads are waiting about 500x longer on the lock than they do for the deque operation to complete.

**Comment by Xophmeister** [comment]
This lock is used to serialise the queue; otherwise threads could dequeue cookies out-of-order. There's a question as to how much this matters: i.e., does this need to be a true FIFO?... Removing the lock entirely would obviously be a quick win.

**Comment by colin-nolan** [comment]
How does this lock ensure any kind of order (AFAIK there is no guarentee that the first to block is the first released)? Furthermore, what order is it supposed to be preserving - that in which cookies are dequeued or that in which threads get a cookie to process?

**Comment by Xophmeister** [comment]
The order of the queue is preserved: The queue is locked to dequeue, then unlocked for other threads.

**Comment by Xophmeister** [comment]
Regardless of the ordering, the dequeue operation is done in two steps, so the lock is needed to make it atomic. This could potentially be done server-side with an update handler. However, these aren't the fastest things in the world, so it might not achieve anything. Will experiment...

**Comment by Xophmeister** [comment]
[Update handlers](http://docs.couchdb.org/en/1.6.1/couchapp/ddocs.html#update-functions) are not designed to work like this: They take a full document (or nothing, for inserts) and modify that document server-side. There is no functionality (afaik) to fetch from a view inside an update handler. Thus there's no way to do this as an atomic action on the server.

I have otherwise just moved the locking code into `_Bert.dequeue`. This shouldn't make any difference, performance-wise, but is arguably a better structure as the Biscuit Tin shouldn't be taking responsibility for this.
