### ISSUE TITLE
Listeners not notified of requeue in `BiscuitTin.mark_as_failed`

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#9]
If a cookie is requeued via `BiscuitTin`'s `mark_as_failed` method, listeners are not informed that there is a new cookie to process.

**Comment by colin-nolan** [comment]
Assertions on listener call counts must also be wrong in related tests.

**Comment by Xophmeister** [comment]
Notification should only occur when the cookie is immediately put on the "to process" queue. With `mark_as_failed`, it comes with a lead time -- which is meant for allowing manual investigation, fixes, etc. to occur -- before it appears back on the queue.

Its reappearance is automatic (based on the timestamp), so a notification can't be sent at that point without polling the DB regularly (or having a similar method running programmatically). It's not relevant to send a notification when it's marked as failed (with the possible exception of the lead time being zero), as there isn't a new cookie to process.

**Comment by colin-nolan** [comment]
I agree that it's no relevant to send a notional when it's marked as failed.

However, a notification must be sent when it is requeued after a delay else it will not be reprocessed. I'm not sure how it's implemented but if it's reappearance is automatic, can the notification also be part of that automaticness?

**Comment by Xophmeister** [comment]
It's automatic in a passive sense. Each document has a `queue_from` timestamp: when (and after) that timestamp has been reached, the document will appear in the view. The point being: There is no "event" that is spawned (or spawnable) by the DB and sent to the application. Thus the only option would be to poll the DB.

That's not a problem, but I believe the reason it was omitted is because what is *now* `enrich_cookie` started off life with a subtly different remit. IIRC, its predecessor was always to be called as a the retriever listener -- which *is* called periodically -- and would process any update (if necessary) and then always broadcast the current queue length. This functionality no longer exists, hence the problem.

**Comment by Xophmeister** [comment]
...In summary: I'll implement DB polling and broadcast the queue length when it's seen to change.

**Comment by colin-nolan** [comment]
I see the issue now...

Given that the DB can only be changed via BiscuitTin, we could use timers, which would be a bit nicer than polling? Might be some clock sync things to consider though.
